sonar.host.url=https://sonarcloud.io
sonar.organization=jbjerome
sonar.projectKey=jbjerome_oc-projet7-cicd
sonar.projectName=microcrm

sonar.sources=back/src/main/java,front/src/app
sonar.tests=back/src/test/java,front/src/app
sonar.test.inclusions=**/*Test.java,**/*Tests.java,**/*.spec.ts

sonar.java.source=17
sonar.java.binaries=back/build/classes/java/main
sonar.java.libraries=back/build/libs/*.jar
sonar.coverage.jacoco.xmlReportPaths=back/build/reports/jacoco/test/jacocoTestReport.xml

sonar.javascript.lcov.reportPaths=front/coverage/microcrm/lcov.info

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/.angular/**
